# Generated by Django 3.0.5 on 2020-04-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Название компании')),
                ('location', models.CharField(default='', max_length=300, verbose_name='Город')),
                ('logo', models.CharField(default='', max_length=300, verbose_name='Логотип')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=300, verbose_name='Код')),
                ('title', models.CharField(max_length=300, verbose_name='Название специализации')),
                ('picture', models.CharField(max_length=300, unique=True, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='Название вакансии')),
                ('skills', models.CharField(default='', max_length=300, verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.PositiveIntegerField(verbose_name='Минимальная з/п')),
                ('salary_max', models.PositiveIntegerField(verbose_name='Максимальная з/п')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='job.Company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_speciality', to='job.Specialty', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
