# Generated by Django 3.0.5 on 2020-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200405_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Изображение'),
        ),
    ]
