# Generated by Django 3.0.5 on 2020-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200406_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(default='', max_length=300, verbose_name='Скилы'),
        ),
    ]
